# Generated by Django 4.0.3 on 2022-03-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=1000)),
                ('ingredient', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=400)),
                ('step', models.CharField(max_length=2000)),
            ],
        ),
    ]
