# Generated by Django 4.0.3 on 2022-03-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user_like',
            field=models.ManyToManyField(related_name='like_recipe', to='socialaccount.socialaccount'),
        ),
    ]
