# Generated by Django 4.0.3 on 2022-03-25 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_recipe_user_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='user_like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
