# Generated by Django 4.0.3 on 2022-03-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_recipe_user_like_recipe_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
