# Generated by Django 4.0.3 on 2022-03-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='step',
            new_name='steps',
        ),
    ]
