# Generated by Django 4.0.3 on 2022-03-26 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_recipe_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
