# Generated by Django 4.0.3 on 2022-04-07 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_recipe_author_alter_recipe_user_likes'),
        ('app', '0008_alter_recipe_user_likes'),
    ]

    operations = [
    ]
