# Generated by Django 4.0.3 on 2022-04-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_recipe_forked_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='forked_from',
            new_name='forked_from_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='forked_from_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
