# Generated by Django 4.0.3 on 2022-04-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_recipe_recipe_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_photo',
            new_name='image',
        ),
    ]
