# Generated by Django 4.0.3 on 2022-04-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_forked_from_recipe_forked_from_id_and_more'),
        ('app', '0016_alter_recipe_image'),
    ]

    operations = [
    ]
