# Generated by Django 4.0.3 on 2022-04-09 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='forked_from_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='forked_from_name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user_forks',
        ),
        migrations.AddField(
            model_name='recipe',
            name='forked_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.recipe'),
        ),
    ]
