# Generated by Django 4.0.3 on 2022-04-09 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_recipe_forked_from_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='forked_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_recipes', to='app.recipe'),
        ),
    ]
