# Generated by Django 4.0.3 on 2022-04-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_recipe_image'),
        ('app', '0020_alter_recipe_forked_from'),
    ]

    operations = [
    ]
