# Generated by Django 4.0.3 on 2022-04-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_comment_recipe_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='recipe_comments', to='app.comment'),
        ),
    ]
