# Generated by Django 4.0.3 on 2022-04-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_recipe_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
