# Generated by Django 4.0.3 on 2022-04-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_merge_20220411_2340'),
        ('app', '0024_comment_recipe_comments'),
    ]

    operations = [
    ]
