# Generated by Django 4.0.3 on 2022-04-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_merge_20220414_1426'),
        ('app', '0025_remove_recipe_comments_comment_recipe'),
    ]

    operations = [
    ]
