# Generated by Django 4.0.3 on 2022-04-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
    ]
